// src/app/layout.tsx
import React from 'react';
import './globals.css'; // Importe seu arquivo de estilos globais, se houver

const RootLayout: React.FC = ({ children }: React.PropsWithChildren<{}>) => {
  return (
    <html lang="en">
      <head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}

export default RootLayout;